//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int TaskID { get; set; }
        public int UserID { get; set; }
        public int AssignmentID { get; set; }
    
        public virtual User User { get; set; }
        public virtual TaskDatabaseTable TaskDatabaseTable { get; set; }
    }
}
